# Mongo-Sync Configurations

local:
  db: 'local_db_name'

remote:
  db: 'remote_db_name'
  host:
    url: 'some.remoteurl.com'
    port: 27017
  access:
  	username: 'remote_mongo_user'
  	password: 'remote_mongo_pass'

# For now :local only accepts DB name
# Assumes DB is at localhost:27017

# All of the parameters above are required,
# without them, the script will fail